name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag lawrenceching/nghttp2:$(date '+%Y-%m-%d')
    - name: Docker Push
      run: |
        docker push lawrenceching/nghttp2:$(date '+%Y-%m-%d')
        docker tag lawrenceching/nghttp2:$(date '+%Y-%m-%d') lawrenceching/nghttp2:latest
        docker tag lawrenceching/nghttp2:latest lawrenceching/h2load:latest
        docker push lawrenceching/nghttp2:latest
        docker push lawrenceching/h2load:latest
